###
# SYSADM Server
# @Author  Wayne Wang <net_use@bzhy.com>Wayne
# @Copyright Bzhy Network
# @HomePage http://www.sysadm.cn
# @Version 0.21.03
# Licensed under the Apache License, Version 2.0 (the Licensed)
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# @License GNU Lesser General Public License  https://www.sysadm.cn/lgpl.html
###

# NOTE: This file be generated by building scripts. DON'T EDIT THIS FILE.
# Generated at: 20210412 10:44:22

GO = GO111MODULE=on go
GOVERSION ?= $(shell go version)
BUILDTIME ?= $(shell date +'%Y.%m.%d.%H%M%S')
GITCOMMIT ?= $(shell git log --pretty=oneline -n 1)
BranchInfo ?= $(shell git rev-parse --abbrev-ref HEAD)
SERVER_GO_FILES ?= $(shell find ./pkg/server ! -name *_test.go  -name *.go -type f )


LDFlags=" \
  -X 'config.Commit=${GITCOMMIT}' \
  -X 'config.BuildBranch=${BranchInfo}' \
	-X 'config.Buildstamp=${BUILDTIME}' \
	-X 'config.goversion=${GOVERSION}' \
"

.PHONY: all server 

all: server install clean

server: ## Build server
	@echo "Building server ..."
	$(GO) build -ldflags $(LDFlags)  -o ./bin/server  $(SERVER_GO_FILES)
